version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on: 
            - db

    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - DB_NAME:m4sdatabasenew
            - DB_USER:m4suser
            - DB_PASSWORD:db@m4s
            - DB_HOST:172.17.0.1
            - DB_PORT:5432
        volumes:
            - .dbdata:/var/lib/postgresql/
        ports:
            - "5432:5432"
        env_file: .env

volumes:
  dbdata:
